const run = () => console.log("");

try {
  run();
} catch (e) {
  console.error("error");
}
