const run = () => console.log("hi");

try {
  run();
} catch (e) {
  console.error("error");
}
